# Workflow to run Docker Compose and deploy to GitHub Pages
name: Docker Compose CI/CD for Tagbooru

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build-and-deploy"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Docker Buildx (optional, for building Docker images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Run Docker Compose to start the service
      - name: Run Docker Compose
        run: |
          docker-compose up -d --build
          # Wait for the service to be ready (adjust timeout as needed)
          sleep 30
          # Optional: Copy static files from the container to the host
          # This assumes your app serves files from a volume or directory like /app/public
          docker cp $(docker-compose ps -q):/app/public ./public || true

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public # Directory to deploy (adjust if different)
